Add component level logging and other changes
JeffersonLab/hps-mc pull request #354
Opened 2023-03-14 01:09 UTC by JeremyMcCormick

This PR adds component level logging. Additionally, the way configuration is loaded was changed so that initialization of the hpsmc package will create a global logger from which other module loggers may inherit. 

n testing, I found that the Job class could not be used without calling the function to parse command line arguments; I updated it so that it could be created manually without the need for argument parsing. 

There are a number of other small bug fixes and cleanup included in the PR as well.

I've tested the changes with a basic dummy job:

```
from hpsmc.component import DummyComponent
from hpsmc.job import Job

j = Job()
j.add(DummyComponent())
j.run()
```

I will test more extensively when I have a chance.

PR is in draft mode for the time being until fully tested. Feel free to leave feedback in the meantime.

2023-03-14 03:01 UTC, JeremyMcCormick commented
Here is sample logging output using the new scheme:

```
hpsmc:INFO Config files found: ['/work/hps/hps-mc/scratch/.hpsmc']
hpsmc.job:INFO Reading additional config from: ['/work/hps/hps-mc/scratch/dummy.cfg']
hpsmc.job:INFO Job ID: None
hpsmc.job:INFO Description: HPS MC Job
hpsmc.job:INFO Job configuration:
[HPSMC]
loglevel=INFO

[Job]
dry_run=False
delete_existing=True
enable_file_chaining=True
check_output_files=True
delete_rundir=False

[DummyComponent]
loglevel=DEBUG

hpsmc.job:INFO Loading job script: ../python/jobs/dummy_job.py
hpsmc.job:INFO Job components loaded: ['dummy']
hpsmc.job:INFO No job parameters were specified!
hpsmc.job:INFO Changing to run dir: /work/hps/hps-mc/scratch
hpsmc.job:INFO Executing 'dummy' with command: dummy
================ Component: dummy ================
hpsmc.component.DummyComponent:DEBUG dummy debug
hpsmc.component.DummyComponent:INFO dummy info
hpsmc.component.DummyComponent:WARNING dummy warn
hpsmc.component.DummyComponent:CRITICAL dummy critical
hpsmc.component.DummyComponent:ERROR dummy error
hpsmc.job:INFO Execution of dummy took 0.0058 second(s) with return code: None
hpsmc.job:INFO Job execution took 0.010637 seconds
hpsmc.job:INFO Running cleanup for component: dummy
hpsmc.job:INFO Successfully finished running job: Dummy
```

The above has global log level (HPSMC) set to INFO with the component at DEBUG.

2023-03-14 19:40 UTC, tomeichlersmith submitted a review, later dismissed
Looks good - I like this update and plan to update my PR https://github.com/JeffersonLab/hps-mc/pull/344 to use it.

2023-03-20 13:26 UTC, tomeichlersmith requested changes
Just a few more cosmetic/doc updates but I think this looks good in general. (Even better than before! lol)

2023-03-20 13:26 UTC, tomeichlersmith commented on python/hpsmc/__init__.py
> +    _global_logger.info("No config files were found at default locations!")
We can make this message just a bit more helpful (also escalating this to a warning).

```suggestion
    _global_logger.warn("No config files were found at default locations! (`~/.hpsmc` or `.hpsmc` in your current directory)")
```

2023-03-20 13:26 UTC, tomeichlersmith commented on python/hpsmc/_logging.py
> +
```suggestion
    """"! setup and configure the logging using the HPSMC block of the passed config

    The parameters 'loglevel' and 'logfile' are checked within the 'HPSMC' block of the config.
    The default loglevel is INFO and the default logfile is the terminal (stdout).
    """
```

2023-03-20 13:26 UTC, tomeichlersmith commented on python/hpsmc/component.py
>  logger = logging.getLogger("hpsmc.component")
Should be deleted - yes?

```suggestion
```

2023-03-20 22:19 UTC, JeremyMcCormick commented
@tomeichlersmith 

Thank you for the detailed suggestions. 

I committed all your proposed changes, as they looked good. This should be ready for final review now.

2023-03-21 14:11 UTC, tomeichlersmith approved these changes

2023-03-24 21:03 UTC, merged